version: '3.8'
services:
  app-api:
    depends_on:
      - db-postgres
    image: app-api
    ports:
      - '8081:3333'
    networks:
      - backend
    environment:
      - POSTGRES_HOST=db-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=api-db
      - NODE_ENV=production
      - SESSION_SECRET=this-is-my-secret-key
      - MS_PORT=4000
      - MS_HOST={DOCKER_HOST}
      - MS_API_PORT=4444
    links:
      - 'db-postgres:database'
  db-postgres:
    image: postgres
    container_name: api-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=api-db
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGADMIN_DEFAULT_EMAIL=user@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - ms-postgres-data:/var/lib/postgres/data
    ports:
      - '5432:5432'
      - '443:443'
      - '80:80'
    networks:
      - backend
networks:
  backend:
volumes:
  ms-postgres-data:
  node-cache:
