version: '3'
services:
  app-api:
    image: app-api
    ports:
      - 8081:3333
    networks:
      - backend
  db-postgres:
    image: postgres
    container_name: api-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=api-db
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
      - 443:443
      - 80:80
    networks:
      - backend
networks:
  backend:
