apiVersion: v1
kind: Template
metadata:
  name: node-build
labels:
  template: node-build
#  app: ${NAME}${SUFFIX}
#  app.kubernetes.io/component: database
#  app.kubernetes.io/name: patroni
#  app.kubernetes.io/managed-by: template
#  app.kubernetes.io/version: "${PG_VERSION}"
parameters:
#  - name: NAME
#    value: patroni
#  - name: SUFFIX
#  - name: OUT_VERSION
#    description: Ouput version
#    value: "v10-latest"
#  - name: GIT_URI
#    value: https://github.com/BCDevOps/platform-services.git
#  - name: GIT_REF
#    value: master
  - name: NODE_VERSION
    value: "14-slim"
objects:
- kind: ImageStream
  apiVersion: image.openshift.io/v1
  metadata:
    name: node
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    name: node:${NODE_VERSION}
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: registry.hub.docker.com/library/node:${NODE_VERSION}
    importPolicy:
      scheduled: true
    name: "${NODE_VERSION}"
    referencePolicy:
      type: Local